In [82]:
# global and local variable
x = 10 #global
def addition():
    y = 10 #local
    print(x + y)
addition()

20


In [83]:
# assign variable 
a, *b, c = [1,2,3,4,5]
a, b, c

(1, [2, 3, 4], 5)

In [84]:
# swapping the variable 
a, b = 5, 6
b , a = a, b
print(a, b)

6 5


In [85]:
if (n := len('hello')) > 3:
    print(n)

5


In [86]:
# Write a program to print every character of a string entered by the user in a new line using a loop
def chara():
    string = str(input('Enter a string'))
    for i in string :
        print(i)
chara()

g
a
u
r
a
v


In [87]:
# Write a program to find the length of the string "machine learning" with and without using len function
name = 'Machine Learning'
length = 0
for i in name:
    length += 1
print(length)
print(len(name))

16
16


In [88]:
# Write a program to check if the word 'orange' is present in the "This is orange juice".
sentence = 'This is orange juice.'
word = 'orange'
def word_sentence():
    Flag = 'True'
    if word in sentence :
        return Flag
    else:
        Flag = 'False'
        return Flag
word_sentence()

'True'

In [89]:
#Write a Python program to count Uppercase, Lowercase, special character, and numeric values in a given string.
word = '11Gaurav@#12'
# initialize 
count_upper = 0
count_lower = 0
count_special = 0 
count_numeric = 0
# apply 
for i in word :
    if i.isupper():
        count_upper += 1
    elif i.islower():
        count_lower += 1
    elif i.isdigit():
        count_numeric += 1
    else:
        count_special += 1
print(count_upper)
print(count_lower)
print(count_numeric)
print(count_special)

1
5
4
2


In [470]:
# Write a program to make a new string with all the consonants deleted from the string "Hello, have a good day".

given_string = "Hello, have a good day"
vovels = 'aeiouAEIOU'

new_string = ''
for i in given_string:
    if i is vovels or not i.isupper() :
        new_string += i
print(new_string)

ello, have a good day


In [91]:
#Write a Python program to remove the nth index character from a non-empty string.
string = 'Gaurav'

def remove_n_index(n):
    result = string[:n] + string[n+1:]
    print(result)
remove_n_index(2)

Garav


In [92]:
# Write a Python program to change a given string to a new string where the first and last characters have been exchanged.
string = 'Gaurav'

def new_string():
    new_string = ''
    first = string[0]
    last = string[-1]
    new_string = last + string[1:-1]  + first
    print(new_string)

# result 
new_string()

vauraG


In [93]:
# Write a Python program to count the occurrences of each word in a given sentence.
sentence = 'Hi my name is gaurav'
occurence = 'm'
count = 0
for i in sentence:
    if i in occurence:
        count += 1
print(count)

2


In [472]:
# Write a Python program to remove a newline in Python
sent = 'Hello\iam\gaurav'
cleaned_string = sent.replace("\n","")
cleaned_string

<>:2: SyntaxWarning: invalid escape sequence '\i'
<>:2: SyntaxWarning: invalid escape sequence '\i'
C:\Users\Gaurav Lute\AppData\Local\Temp\ipykernel_33572\767321506.py:2: SyntaxWarning: invalid escape sequence '\i'
  sent = 'Hello\iam\gaurav'


'Hello\\iam\\gaurav'

In [95]:
# Write a Python program to swap commas and dots in a string ○ Sample string: "32.054,23" ○ Expected Output: "32,054.23"

input_string = "32.054,23"
temp_string = input_string.replace('.','#')
#print(temp_string)
temp_string = temp_string.replace(',','.')
#print(temp_string)
output_string = temp_string.replace('#',',')
#output_string = input_string.replace(',.', '.,')
print(output_string)

32,054.23


In [96]:
# 24. Write a Python program to find the first repeated character in a given string
string = 'pythonprogramming'

repeated = set()
for i in string:
    if i in repeated:
        print(i)
        break
    repeated.add(i)
else:
    print('No repeated count.')

p


In [97]:
# Write a Python program to find the second most repeated word in a given string
word = 'gaurav'
word_count = {}

for i in word:
    if i in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1
print(word_count)
sorted_word = sorted(word_count.items(), key=lambda x: x[1], reverse=True)
print(sorted_word)

if len(sorted_word) < 2:
    print("Not enough unique words.")
else:
    second_most_word, count = sorted_words[1]
    print("Second most repeated word:", second_most_word)
    print("Frequency:", count)

{'gaurav': 1}
[('gaurav', 1)]
Not enough unique words.


In [98]:
#Python program to Count Even and Odd numbers in a string

number = '126478'
even_count = 0
odd_count = 0
for i in number:
    #print(i)
    if int(i)% 2 == 0 :
        even_count += 1
    else:
        odd_count += 1
print(even_count, odd_count)

4 2


In [99]:
#How do you check if a string contains only digits?

s = "12345"
if s.isdigit():
    print("The string contains only digits.")
else:
    print("The string does not contain only digits.")

The string contains only digits.


In [100]:
# How do you remove a given character/word from String?

string = 'gaurav'
char = 'g'
filter_str = string.replace('g',"")
print(filter_str)

aurav


In [101]:
# Write a Python program to remove the characters which have odd index values of a given string.
word = 'gaurav'
new_string = ''
for i in range(len(word)):
    if i % 2 != 0:
        print(word[i], end='')

arv

In [102]:
# Write a Python function to reverses a string if its length is a multiple of 5
string = 'gaurav'
new_string = ''
def length():
    if len(string) % 5 == 0:
        print(string[::-1])
    else:
        print(string)
length()

gaurav


In [103]:
# Write a Python program to format a number with a percentage(0.05 >> 5%)
number = 0.05
percentage = '{:.0%}'.format(number)
print(percentage)

5%


In [104]:
# Write a Python program to reverse words in a string
string = 'gaurav'
reversed = string[::-1]
print(reversed)

for i in range(len(string)-1, -1, -1):
    print(string[i], end='')

varuag
varuag

In [105]:
# 33. Write a Python program to swap cases of a given string
string = 'gaurav'
swap = string.swapcase()
print(swap)

GAURAV


In [106]:
# Write a Python program to remove spaces from a given string

string = 'Gaurav Lute P'
new_string = string.replace(" ", "")
print(new_string)

GauravLuteP


In [107]:
#35. Write a Python program to remove duplicate characters of a given string
# Input from user
input_string = 'gaurav'

# Create an empty result string and a set to track seen characters
result = ""
seen = set()

# Loop through each character
for char in input_string:
    if char not in seen:
        result += char
        seen.add(char)

# Output result
print("String after removing duplicates:", result)


String after removing duplicates: gaurv


In [108]:
# Write a Python Program to find the area of a circle
import numpy as np 

def area_circle(r):
    result = np.pi * r**2
    print(result)

area_circle(3)

28.274333882308138


In [109]:
# Python Program to find Sum of squares of first n natural numbers
n = 5
for i in range(n):
    print(i,'>>>>>' ,i*i)

0 >>>>> 0
1 >>>>> 1
2 >>>>> 4
3 >>>>> 9
4 >>>>> 16


In [110]:
#Python Program to find cube sum of first n natural numbers
n = 5
for i in range(n+1):
    print(i**3)

0
1
8
27
64
125


In [111]:
#Python program to check whether a number is Prime or not
def isprime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True 
isprime(9)

False

In [112]:
def isprime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

# Test
print(isprime(13))  # Output: True


True


In [113]:
def isprime(n):
    if n <= 1:
        return False 
    for i in range(2, n):
        if n % i == 0:
            return False
            break
    return True
isprime(11)

True

In [114]:
def isprime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
            break
    return True
isprime(7)

True

In [115]:
# Assignment 2 List and Tuple 

In [116]:
# list is mutable , tuple is unmutable 

In [476]:
# Python Program to find the largest element in the list
l1 = [1,2,3,9,6,7,8,99]
largest = l1[0]

for i in l1:
    if largest < i:
        largest = i 
        
print(largest)

99


In [118]:
# Python program to interchange first and last elements in a list.# Python program to swap two elements in a list
l1 = [1,2,3,4,5,6,7,8]
l1[0], l1[-1] = l1[-1], l1[0]

In [119]:
#  Python program to Reverse a List
l1 = [1,2,3,4,5,6,7,8]
reversed = l1[::-1]
reversed

[8, 7, 6, 5, 4, 3, 2, 1]

In [120]:
#  Python program to count occurrences of an element in a list
l1 = [1,2,3,4,4,5,6,7]
occurence = 4 
count = 0
for i in l1:
    if occurence == i:
        count += 1
print(count)
print(l1.count(occurence))

2
2


In [121]:
# Python program to find the sum of elements in a list
l1 = [1,2,3,4,5,6,7,8,9]
sum_element = 0
for i in l1:
    sum_element += i
print(sum_element)

45


In [122]:
#  Python program to Multiply all numbers in the list
l1 = [1,2,3,4,5,6,7,8,9,9,2]
mul_l1 = 1
for i in l1:
    mul_l1 *= i
print(mul_l1)

6531840


In [123]:
# What are the ways to find the length of a list
l1 = [1,2,3,4,5,6]
print(len(l1))
count = 0
for i in l1:
    count += 1
print(count)

6
6


In [124]:
#Python program to find the smallest and largest number in a list (Without min-max function)

l1 = [1,2,3,4,5,6,7,89,9]

min_no = l1[0]
max_no = l1[0]

for i in l1:
    if min_no > i :
        min_no = i
    elif max_no < i:
        max_no = i

print(min_no)
print(max_no)


1
89


In [125]:
# Python Program to find the area of a circle
def area_circle(r):
    return 3.14*r**2
area_circle(5)

78.5

In [126]:
# Take inputs from the user to make a list. Again take one input from the user and search it in the list and delete that element, 
# if found. Iterate over a list using for loop.

l1 = [1,2,3,4,5,6,7,8]
element = 2

for i in l1:
    if element == i:
        l1.remove(i)
print(l1)

[1, 3, 4, 5, 6, 7, 8]


In [127]:
'''
You are given a list of integer elements. Make a new list that will store a
 square of elements of the previous list. (With and without list comprehension)
 i. Input_list = [2,5,6,12]
 ii. Output_list = [4,25,36,144]
'''
l1 = [1,2,3,4,5,6]
l2 = []
for i in l1:
    res = i*i
    l2.append(res)
print(l2)


[1, 4, 9, 16, 25, 36]


In [128]:
# WAP to create two lists, one containing all even numbers and the other containing all odd numbers between 0 to 151
l1 = [1,2,3,4,5,6,7,8,9,10]
l1_odd = []
l1_even = []
for i in l1:
    if i % 2 == 0:
        l1_even.append(i)
    else:
        l1_odd.append(i)
print(l1_even)
print(l1_odd)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [129]:
# WAP to make new lists, containing only numbers which are divisible by 4, 6, 8, 10, 3, 5, 7, and 9 in separate lists for range(0,151)

l1 = [i for i in range(0, 151)]
l2 = [4,6,8,10,3,5,7,9]

new_list = []
for i in l1:
    for j in l2:
        if i % j == 0 and i not in new_list:
            new_list.append(i)

print(new_list)

[0, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 24, 25, 27, 28, 30, 32, 33, 35, 36, 39, 40, 42, 44, 45, 48, 49, 50, 51, 52, 54, 55, 56, 57, 60, 63, 64, 65, 66, 68, 69, 70, 72, 75, 76, 77, 78, 80, 81, 84, 85, 87, 88, 90, 91, 92, 93, 95, 96, 98, 99, 100, 102, 104, 105, 108, 110, 111, 112, 114, 115, 116, 117, 119, 120, 123, 124, 125, 126, 128, 129, 130, 132, 133, 135, 136, 138, 140, 141, 144, 145, 147, 148, 150]


In [130]:
# From a list containing ints, strings, and floats, make three lists to store them separately
l1 = [1,2,3,'q','a','l', 3.14, 5.33]
l1_int = []
l1_str = []
l1_float = []

for i in l1:
    if type(i) == int :
        l1_int.append(i)
    elif type(i) == str:
        l1_str.append(i)
    elif type(i) == float:
        l1_float.append(i)

print(l1_int)
print(l1_str)
print(l1_float)

[1, 2, 3]
['q', 'a', 'l']
[3.14, 5.33]


In [131]:
# What’s The Difference Between The Python append() and extend() Methods?
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]

l1.append(l2)
print(l1)

l1.extend(l2)
print(l1)

[1, 2, 3, 4, 5, [2, 3, 4, 5, 6]]
[1, 2, 3, 4, 5, [2, 3, 4, 5, 6], 2, 3, 4, 5, 6]


In [132]:
#  Write a Python program to append a list to the second list
l1 = [1,2,3,45,6]
l2 = [2,4,5]

l1.append(l2)
print(l1)

[1, 2, 3, 45, 6, [2, 4, 5]]


In [133]:
# Write a Python program to find the third-largest number in a list
l1 = [12,15,10,17,25]
third_lar = sorted(l1)

print(third_lar)
third_lar[-3]

[10, 12, 15, 17, 25]


15

In [134]:
#  Write a Python program to get the frequency of the elements in a list.
l1 = [2,2,3,4,5,5,7,8,9,0,2,2,2,3]

frequency = {}
for i in l1:
    if i in frequency:
        frequency[i] += 1
    else:
        frequency[i] = 1
print(frequency)

{2: 5, 3: 2, 4: 1, 5: 2, 7: 1, 8: 1, 9: 1, 0: 1}


In [135]:
# Write a Python program to check whether a list contains a sublist
l1 = [1,2,3,[3,4,5],6,7]


In [136]:
# Function to generate all sublists
def generate_sublists(lst):
    sublists = []
    for i in range(len(lst) + 1):
        for j in range(i):
            sublists.append(lst[j:i])
    return sublists

# Example list
my_list = [1, 2, 3]

# Generate and print all sublists
all_sublists = generate_sublists(my_list)
print("All sublists:")
for sub in all_sublists:
    print(sub)


All sublists:
[1]
[1, 2]
[2]
[1, 2, 3]
[2, 3]
[3]


In [137]:
# Write a Python program to find common items from two lists.
l1 = [1,1,2,3,4,4,5]
l2 = [1,23,3,4]
common = []
for i in l1:
    if i in l2 and i not in common:
        common.append(i)
print(common)


[1, 3, 4]


In [138]:
# How to flatten a list in python?
l1 = [[1,2],[3,4],[5,6],[7,8,9]]
l2 = []
for i in l1:
    for j in i:
        l2.append(j)
l2

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [139]:
# How to sort a list in ascending and descending order without using the sort function?
l1 = [4, 2, 7, 1, 5]
asending = []
desending = []

for i in range(len(l1)):
    for j in range(i +1, len(l1)):
        if l1[i] > l2[j]:
            l1[i], l1[j] = l1[j], l1[i]
print(l1)

[2, 1, 4, 5, 7]


In [140]:
#How to sort a tuple?
l1 = (1,3,2)

l2 = list(l1)
l2.sort() # descending order l2.sort(reverse=True)

l3 = tuple(l2)
l3

(1, 2, 3)

In [141]:
# Write a Python program to convert a list of multiple integers into a single integer a. [11, 33, 50] >>>  113350

l1 = [11, 33, 50]
l2 = []

result = int(''.join(str(num) for num in l1))
print(result)

113350


In [142]:
# Difference between del and clear?
l1 = [1,2,3,4,5,6]
del l1[0]
l1


[2, 3, 4, 5, 6]

In [143]:
l1.clear()
l1

[]

In [144]:
# Difference between remove and pop?
l1 = [1,2,3,4,5,6]
removed = l1.remove(1)
print(removed)

ppop = l1.pop(1)
print(ppop)

None
3


In [145]:
#  Difference between indexing and Slicing?

l1 = [1,2,3,4]
# indexing 
index = l1[0]
print(index)
# slicing 
slicing = l1[1:2] #[start:end:step]
print(slicing)

1
[2]


In [146]:
# Difference between sort and sorted? 
l1 = [1,2,37,5,6]
# sort 
l1.sort() # original list directly change
l1

[1, 2, 5, 6, 37]

In [147]:
l2 = [1,23,10,15]
l22=sorted(l2) # not change original list 
l22

[1, 10, 15, 23]

In [148]:
# Difference between reverse and reversed?
l1 = [1,2,3,54,6, 48]
l1.sort()
l1

[1, 2, 3, 6, 48, 54]

In [149]:
l1 = [1,2,3,54,6, 48]
l2 = sorted(l1)
l2

[1, 2, 3, 6, 48, 54]

In [150]:
# copy and deepcopy
l1 = [1,2,3,4,5,6]
co = l1.copy()
co

[1, 2, 3, 4, 5, 6]

In [151]:
# How to check whether the list is empty or not? 
l1 = [1,2,3,4,5,6]

if len(l1) == 0:
    print('Empty')
else:
    print('Not empty')

Not empty


In [152]:
# How to concatenate two lists?
l1 = [1,2,3,4]
l2 = [4,5,6,7]

mix = l1 + l2
print(mix)

[1, 2, 3, 4, 4, 5, 6, 7]


In [153]:
#  How to find the occurrences of an element in the python list?

l1 = [1,2,3,4,5,6,7,8]
element = 2
for i in l1 :
    if element == i :
        print('Occured', end='')
    else:
        print(' Not ', end='')

 Not Occured Not  Not  Not  Not  Not  Not 

In [154]:
# How to flatten a list in python?
l1 = [[1,2,3], [3,4,5], [6,7,8]]

for i in l1:
    for j in i:
        print(j, end='')

123345678

In [155]:
# Dictionary 

In [156]:
# Sample dictionary
my_dict = {'banana': 3, 'apple': 1, 'cherry': 2, 'date': 4}

# Sort dictionary by keys
sorted_dict = dict(sorted(my_dict.items()))

# Display the sorted dictionary
print("Sorted by keys:", sorted_dict)

Sorted by keys: {'apple': 1, 'banana': 3, 'cherry': 2, 'date': 4}


In [157]:
# Python program to sort Python Dictionaries by Values
my_dict = {'banana': 2, 'apple': 1, 'cherry': 2, 'date': 4}

# sorted by values 
sorted_dict = dict(sorted(my_dict.items(), key= lambda x: x[1]))
print(sorted_dict)

{'apple': 1, 'banana': 2, 'cherry': 2, 'date': 4}


In [158]:
# Python program to find the sum of all items in a dictionary
sum_dic = sum(my_dict.values())
print(sum_dic)

9


In [159]:
# Python program to remove a key from a dictionary
#my_dict

del my_dict['apple']


In [160]:
my_dict

{'banana': 2, 'cherry': 2, 'date': 4}

In [161]:
# Python program to merge two Dictionaries
dict1 = {'a':1, 'b': 2, 'c' :3}
dict2 = {'d':4, 'e':5, 'f':6}

mix = dict1.update(dict2)
print(dict1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


In [162]:
#  Program to create grade calculator in Python
# Get number of subjects
num_subjects = int(input("Enter number of subjects: "))

# Initialize total
total = 0

# Take input for each subject
for i in range(1, num_subjects + 1):
    marks = float(input(f"Enter marks for subject {i}: "))
    total += marks

# Calculate average
average = total / num_subjects

# Determine grade
if average >= 90:
    grade = 'A+'
elif average >= 80:
    grade = 'A'
elif average >= 70:
    grade = 'B'
elif average >= 60:
    grade = 'C'
elif average >= 50:
    grade = 'D'
else:
    grade = 'F'

# Output
print(f"\nTotal Marks = {total}")
print(f"Average = {average:.2f}")
print(f"Grade = {grade}")



Total Marks = 20.0
Average = 20.00
Grade = F


In [163]:
# Print anagrams together in Python using List and Dictionary
word = ["bat", "tab", "tap", "pat", "cat", "act"]

anagram_dict = {}

for word in word:
    key = ''.join(sorted(word))
    if key in anagram_dict:
        anagram_dict[key].append(word)
    else:
        anagram_dict[key] = [word]

for group in anagram_dict.values():
    print(group)

['bat', 'tab']
['tap', 'pat']
['cat', 'act']


In [164]:
#  Check if binary representations of two numbers are an anagram
def are_binary_anagrams(num1, num2):
    bin1 = bin(num1)[2:]
    bin2 = bin(num2)[2:]

    return sorted(bin1) == sorted(bin2)

num1 = 2
num2 = 3
are_binary_anagrams(num1, num2)

False

In [165]:
# Python Counter to find the size of the largest subset of anagram words
from collections import Counter

def largest_anagram_subset(words):
    sorted_word = [''.join(sorted(words)) for word in words]
    word_count = Counter(sorted_word)
    return max(word_count.values())
words = ["bat", "tab", "tap", "pat", "cat", "act"]
print("Size of largest anagram subset:", largest_anagram_subset(words))

Size of largest anagram subset: 6


In [166]:
def mirror_characters(s):
    # Create mirror dictionary for lowercase letters
    mirror = {chr(i): chr(219 - i) for i in range(97, 123)}  # a-z

    # You can also include uppercase if needed
    mirror.update({chr(i): chr(155 - i) for i in range(65, 91)})  # A-Z

    # Build the mirrored string
    mirrored = ''.join(mirror.get(ch, ch) for ch in s)
    
    return mirrored

# Example usage
input_str = "abcXYZ"
output_str = mirror_characters(input_str)
print("Original:", input_str)
print("Mirrored:", output_str)


Original: abcXYZ
Mirrored: zyxCBA


In [167]:
#  Counting the frequencies in a list using a dictionary in Python
def count_ferquency(l1):
    freq_dict = {}
    for i in l1:
        if i in freq_dict:
            freq_dict[i] += 1
        else:
            freq_dict[i] = 1
    return freq_dict

# Example usage
sample_list = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']
frequencies = count_ferquency(sample_list)

print("Frequencies:", frequencies)

Frequencies: {'apple': 3, 'banana': 2, 'orange': 1}


In [168]:
#  Scraping And Finding Ordered Words In A Dictionary using Python


In [169]:
#  Create a list of tuples from the given list having a number and its cube in each tuple
l1 = [1,2,3,4]
l2 = []
for i in l1:
    result = (i, i**3)
    l2.append(result)
print(result)
print(l2)

(4, 64)
[(1, 1), (2, 8), (3, 27), (4, 64)]


In [170]:
#  Sort a list of tuples by the second Item
sample_list = [(1, 3), (2, 1), (4, 5), (3, 2)]

sorted_list = sorted(sample_list, key = lambda x:x[0])
print(sorted_list)

[(1, 3), (2, 1), (3, 2), (4, 5)]


In [171]:
#  Python Program for Insertion Sort
def insertion_sort(arr):
    for i in range(1, len(arr)):
        for j in range(i, 0, -1):
            if arr[j] < arr[j - 1]:
                arr[j], arr[j - 1] = arr[j - 1], arr[j]
            else:
                break

# Example usage
nums = [8, 4, 2, 9, 5]
insertion_sort(nums)
print("Sorted list:", nums)

Sorted list: [2, 4, 5, 8, 9]


In [172]:
#  Python Program for SelectionSort
arr = [64, 25, 12, 22, 11]
n = len(arr)

for i in range(n):
    min_index = i
    for j in range(i+1, n):
        if arr[j] < arr[min_index]:
            min_index = j
    arr[i], arr[min_index] = arr[min_index], arr[i]

print("Sorted list:", arr)


Sorted list: [11, 12, 22, 25, 64]


In [173]:
# Python bubble sort
arr = [64, 34, 25, 12, 22, 11, 90]
n = len(arr)

for i in range(n):
    for j in range(0, n - i - 1):
        if arr[j] > arr[j + 1]:
            # Swap if the element found is greater than the next element
            arr[j], arr[j + 1] = arr[j + 1], arr[j]

print("Sorted list:", arr)

Sorted list: [11, 12, 22, 25, 34, 64, 90]


OOPs

In [174]:
#  What Is Object-Oriented Programming?
# oops contains class and atributes.
class Car:
    def __init__(self, brand, name):
        self.brand = brand
        self.name = name

    def drive(self):
        print(self.brand, self.name)

car = Car('Toyota', 'Fortuner')
print(car.drive())


Toyota Fortuner
None


In [175]:
# Inheritance 
class Animal:
    def speaks(self):
        print('Animal Sound')
class Dog(Animal):
    def speaks(self):
        print('Bark')
print(Animal())
res = Animal()
res1 = Dog()
print(res1.speaks())

Bark
None


In [176]:
class Shape:
    def draw(self):
        print("Drawing shape")

class Circle(Shape):
    def draw(self):
        print("Drawing circle")

class Square(Shape):
    def draw(self):
        print("Drawing square")

# Polymorphism in action
shapes = [Circle(), Square()]
for shape in shapes:
    shape.draw()

Drawing circle
Drawing square


In [177]:
# What is objects 
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
    def bark(self):
        print(f'{self.name} say wolf')

dog1 = Dog('Buddy', 'Golden Retriever')
dog2 = Dog('Max', 'Labrador')

dog1.bark()
dog2.bark()

Buddy say wolf
Max say wolf


In [178]:
# Numpy 

In [179]:
#1. Create a null vector of size 10
import numpy as np 
array = np.zeros(10)
print(array)
#2. How to find the memory size of an array
array.nbytes

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


80

In [180]:
#  3. Create a null vector of size 10 but the fifth value which is 1
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [181]:
#4. Create a vector with values ranging from 15 to 45
arr = np.arange(15,45)
arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [189]:
#  5. Reverse a vector (The first element becomes last)
vector = np.arange(1,6)
resevse_vector = vector[::-1]
resevse_vector

array([5, 4, 3, 2, 1])

In [192]:
#  6. Write a NumPy program to add, subtract, multiply, divide arguments element-wise 7.
a = np.array([1,2,34,5])
b = np.array([5,6,7,80])

add = np.add(a,b)
sub = np.subtract(a,b)
mul = np.multiply(a,b)
div = np.divide(a,b)

print(add, sub, mul, div)

[ 6  8 41 85] [ -4  -4  27 -75] [  5  12 238 400] [0.2        0.33333333 4.85714286 0.0625    ]


In [194]:
#  Write a NumPy program to round elements of the array to the nearest integer.
arr = np.array([1.2,1.5, 2.5, 3.5, 4.6])

r = np.round(arr)
print(r)

[1. 2. 2. 4. 5.]


In [201]:
# Write a NumPy program to get the floor and ceiling values of the elements of a NumPy array.
floar = np.floor(arr)
print(floar)
celing = np.ceil(arr)
print(celing)

[1. 1. 2. 3. 4.]
[2. 2. 3. 4. 5.]


In [208]:
#  9. Write a NumPy program to calculate mean across dimensions, in a 2D NumPy array. 
array1 = np.array([[1,2,3,4],[4,5,6,7]])
mean = np.mean(array1)
mean

np.float64(4.0)

In [211]:
#  Write a NumPy program to convert angles from degrees to radians for all elements in a given array.
arr = np.array([1,2,3,4,5])
radian = np.deg2rad(arr)
print(radian)

[0.01745329 0.03490659 0.05235988 0.06981317 0.08726646]


In [212]:
# 11. What is the use of all and any function in numpy?
a = np.array([1, 2, 3, 0])

print(np.all(a > 0))  # False (because 0 is not > 0)
print(np.any(a > 2))  # True (because 3 is > 2)


False
True


In [226]:
#  Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [241]:
# How to reverse the columns of a 2D array?
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_column = arr[:,::-1]
print(reversed_column)
reversed_row = arr[::-1,:]
print(reversed_row)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [239]:
#  15. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)


In [242]:
#  16. Write a NumPy program to compute the determinant of an array.
determinant = np.linalg.det(arr)
print(determinant)

0.0


In [248]:
# 17. Write a NumPy program to compute the inverse of a given matrix
arr = np.array([[1,2],[4,5]])
np.linalg.inv(arr)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [256]:
#  18. Create a random vector of size 30 and find the mean value
vector = np.random.randint(30)
mena_vec = np.mean(vector)
mena_vec

np.float64(2.0)

In [259]:
#  19. How to extract all numbers between a given range from a NumPy array?
arr = np.array([1,3,5,7,11,13,15])
filtered_arry = arr[(arr >= 5) & (arr <= 10)]
filtered_arry

array([5, 7])

In [264]:
#  20. Create a 3x3x3 array with random values
arr = np.random.randn(30)
arr

array([ 0.45303564, -0.73464699,  0.24235035, -0.63404773, -0.08764959,
        1.23115741,  1.20439193,  1.88460251,  0.95185453, -1.10690301,
        0.17960539,  1.00075234,  1.93907941, -1.16293424,  0.66486488,
       -0.05545283, -0.05326525, -0.2041292 ,  2.83250344, -0.48960773,
       -0.23069729,  0.44269787, -1.63080747, -0.77007214,  1.75788754,
       -0.5279664 , -0.74645806, -1.07502407, -0.5552062 ,  0.30551606])

In [269]:
#  20. Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))
random_array

array([[[0.87823989, 0.55809714, 0.46173957],
        [0.22888367, 0.79648324, 0.04557916],
        [0.00310374, 0.64601331, 0.77903429]],

       [[0.09258507, 0.79480583, 0.56223104],
        [0.9928602 , 0.84100429, 0.14482196],
        [0.29711847, 0.57972532, 0.05513155]],

       [[0.49751   , 0.63214347, 0.52616913],
        [0.01316928, 0.58574448, 0.51915923],
        [0.22358059, 0.52941486, 0.57372781]]])

In [276]:
#  21. Create a 10x10 array with random values and find the minimum and maximum values
array = np.random.random((10,10))
np.min(array), np.max(array)

(np.float64(0.008650039046376734), np.float64(0.9870066172750807))

In [281]:
#  22. Create a 2d array with 1 on the border and 0 inside
array = np.ones((5,5))

array[1:-1, 1:-1] = 0
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [285]:
#  23. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
# Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal
matrix = np.zeros((5, 5))  # Initialize a 5x5 matrix with zeros

# Assign values just below the diagonal
matrix[1:, :-1] = np.diag([1, 2, 3, 4], -1)


ValueError: could not broadcast input array from shape (5,5) into shape (4,4)

In [287]:
np.eye(3) # Idenntity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [291]:
#  29. How to find common values between the two arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

inters = np.intersect1d(arr1, arr2)
inters

array([5])

In [293]:
# Create two random arrays A and B
A = np.random.rand(3, 3)  # 3x3 array with random values
B = np.random.rand(3, 3)  # 3x3 array with random values

# Check if the arrays are equal
are_equal = np.array_equal(A, B)
print(are_equal)

False


In [296]:
# # 2D array
arr = np.array([[3, 1, 2],
                [1, 5, 4],
                [2, 2, 6]])
sorted_arr = arr[arr[:,1].argsort()]
sorted_arr

array([[3, 1, 2],
       [2, 2, 6],
       [1, 5, 4]])

In [303]:
# How to compute the mode of a NumPy array
import numpy as np 
from scipy import stats

arr = np.array([1,2,2,3,4,5,6,7,8,9])

mode_result = stats.mode(arr, keepdims=False)
mode_result.mode

np.int64(2)

In [317]:
#  Write a NumPy program to compute the inverse of a given matrix 45
array1 = np.array([[2, 1, 1],
                      [1, 3, 2],
                      [1, 0, 0]])

inverse_matrix = np.linalg.inv(array1)
inverse_matrix

array([[ 0.,  0.,  1.],
       [-2.,  1.,  3.],
       [ 3., -1., -5.]])

In [320]:
# 45. Write a NumPy program to compute the covariance matrix of two given arrays

matrix = np.array([[1,2,3,4],[5,6,7,8]])
covariance = np.cov(matrix)
covariance

array([[1.66666667, 1.66666667],
       [1.66666667, 1.66666667]])

In [326]:
#  How to find the most frequent value in a NumPy array
from scipy import stats
array = np.array([1,2,3,3])
most = stats.mode(array, keepdims=False)
most.mode

np.int64(3)

Pandas 

In [330]:
#  Define the Pandas/Python pandas
# creating a dataframe 
import pandas as pd
data = {'name':['gaurav','lute','patil'], 'Age':[22,23,42]}
df = pd.DataFrame(data)
df.head()

name  Age
0  gaurav   22
1    lute   23
2   patil   42

In [332]:
age_column = df['Age']
age_column

0    22
1    23
2    42
Name: Age, dtype: int64

In [336]:
df.iloc[0]

name    gaurav
Age         22
Name: 0, dtype: object

In [338]:
df.dropna()
df.fillna(0)

name  Age
0  gaurav   22
1    lute   23
2   patil   42

In [342]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Value': [10, 20, 30]})
df2 = pd.DataFrame({'ID': [1, 2, 3], 'Value': [100, 200, 300]})
df_merge = pd.merge(df1, df2, on='ID')
df_merge

ID  Value_x  Value_y
0   1       10      100
1   2       20      200
2   3       30      300

In [343]:
df1.groupby('ID').mean()

Value
ID       
1    10.0
2    20.0
3    30.0

In [346]:
# How Can You Create An Empty DataFrame and series in Pandas?
df_empty = pd.DataFrame()
df_empty

Empty DataFrame
Columns: []
Index: []

In [348]:
# How to check an empty DataFrame
df.empty

False

In [354]:
# Reindexing 
df = pd.DataFrame({'Name':['Gaurav','Harshal', 'Shubham'], 'Age':[22,23,35]}, index=[0,1,2])
df.head()
df_reindex = df.reindex([2,0,1])
df_reindex

Name  Age
2  Shubham   35
0   Gaurav   22
1  Harshal   23

In [356]:
df = df.rename(columns={'Name':'N', 'Age':'A'})
df

N   A
0   Gaurav  22
1  Harshal  23
2  Shubham  35

In [357]:
df['N'].tolist()

['Gaurav', 'Harshal', 'Shubham']

In [ ]:
#Write a Pandas program to read specific columns from a given excel file
# df = pd.read_csv('data.csv', usecols=['columns1','columns2'])

N   A
0   Gaurav  22
1  Harshal  23
2  Shubham  35

In [367]:
# gropuby function
data = {
    'Product': ['A', 'B', 'A', 'B', 'A'],
    'Sales': [100, 200, 150, 300, 250]}
df = pd.DataFrame(data)
sales_mean = df.groupby('Product')['Sales'].sum()
sales_mean

Product
A    500
B    500
Name: Sales, dtype: int64

In [368]:
# What is the use of apply function in pandas?
df.apply(lambda x: x.sum(), axis=0)

Product    ABABA
Sales       1000
dtype: object

In [371]:
#map function 
df['Sales'] = df['Sales'].map(lambda x: x**2)
df

Product       Sales
0       A   100000000
1       B  1600000000
2       A   506250000
3       B  8100000000
4       A  3906250000

In [378]:
#  How will you add a column to a pandas DataFrame?
df.head()
df['Country'] = 'IND'


In [379]:
# How to remove columns 
# df.drop(colums =['',''], inplace = True)

In [381]:
# Sample Series
data = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data.describe()

count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

In [383]:
#  How can we sort the DataFrame?
df.sort_values(by='Sales')

Product       Sales Country
0       A   100000000     IND
2       A   506250000     IND
1       B  1600000000     IND
4       A  3906250000     IND
3       B  8100000000     IND

In [385]:
#  How to drop duplicate rows from DataFrame?

df.drop_duplicates()

Product       Sales Country
0       A   100000000     IND
1       B  1600000000     IND
2       A   506250000     IND
3       B  8100000000     IND
4       A  3906250000     IND

In [386]:
# fill nul value 
df['Sales'].fillna(df['Sales'].mean())

0     100000000
1    1600000000
2     506250000
3    8100000000
4    3906250000
Name: Sales, dtype: int64

In [387]:
# find str
df['Product'].str.len()

0    1
1    1
2    1
3    1
4    1
Name: Product, dtype: int64

In [388]:
 df = pd.DataFrame({
 'company_code': ['c0001','c0002','c0003', 'c0003', 'c0004'],
 'year': ['year 1800','year 1700','year 2300', 'year 1900', 'year 2200']
 })

In [391]:
# Write a Pandas program to join the two given dataframes along rows
df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)
df_combined

ID  Value
0   1     10
1   2     20
2   3     30
3   1    100
4   2    200
5   3    300

In [424]:
# 
l1 = '1,2,3,4'
l2 = list(l1)
l3 = []
for i in range(len(l2)):
    if i % 2 == 0:
        #print(l2[i])
        l3.append(l2[i])
l4 = []
for i in l3:
    if type(i) == str:
        l4.append(int(i))

Average = sum(l4) / len(l4)
print(Average)

2.5


In [432]:
df['path'] = 0
df

company_code       year  path
0        c0001  year 1800     0
1        c0002  year 1700     0
2        c0003  year 2300     0
3        c0003  year 1900     0
4        c0004  year 2200     0

In [464]:
# factorial 
n = 5
factorial = 1
for i in range(1, n+1):
    factorial *= i
    print(factorial)

1
2
6
24
120


In [468]:
# fibonachhi 
n = 10
a, b = 0, 1
for i in range(n+1):
    a = b 
    b = a + b 
    print(a)

1
2
4
8
16
32
64
128
256
512
1024


In [5]:
from sklearn import datasets

data = datasets.load_iris()

X = data.data
y = data.target

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2 ,random_state=42)

In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [25]:
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

1.0